from enum import Enum


class ErrorCode(Enum):
    """Error codes for improved error classification."""

    NETWORK_ERROR = "NETWORK_ERROR"
    AUTH_ERROR = "AUTH_ERROR"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    RATE_LIMIT_ERROR = "RATE_LIMIT_ERROR"
    NOT_FOUND = "NOT_FOUND"
    RESPONSE_TOO_LARGE = "RESPONSE_TOO_LARGE"
    UNSAFE_RESPONSE_ENCODING = "UNSAFE_RESPONSE_ENCODING"
    UNKNOWN_ERROR = "UNKNOWN_ERROR"
